name: Audodoc workflow artifacts
description: 'Auto documenting workflow artifacts table in README.md.'

author: Dinesh Sonachalam <dineshsonachalam@gmail.com>

inputs:
  branch:
    description: Git branch name, where changes should be pushed too.
    required: false
    default: ${{ github.ref }}

  output_file_path:
    description: Local file path to the README.md. Defaults to the root of the repo (`./README.md`)
    required: false
    default: './README.md'

runs:
  using: composite
  steps:
    - run: sudo npm i -g markdown-autodocs-test
      shell: bash
    - run: markdown-autodocs-test -c workflow-artifact-table -o ${{ inputs.output_file_path }} -r ${{ github.repository }} -b ${{ inputs.branch }}  -a ${{ github.token }} 
      shell: bash  
      
branding:
  icon: 'package'
  color: blue
