name: autodoc-workflow-artifacts

on:
  workflow_run:
    workflows: ["publish-to-npm"]
    types: [completed]
  push:
    branches:
      - master
    tags:
      - latest

jobs:        
  autoupdate-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: |
            sudo npm i -g autodoc-workflow-artifacts
            autodoc-workflow-artifacts --repo $GITHUB_REPOSITORY --branch $GITHUB_REF --accessToken ${{ secrets.GITHUB_TOKEN }} --inputFilePath ./readme.md

