name: Example

on:
  push:
    branches:
      - master

jobs:

  example:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Test
          run: |
            echo ${{ github.ref }}
            echo ${{ github.repository }}
