name: Integration-Test

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  integration-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Start integration test
          env: 
            TEST_REPO: ${{ secrets.TEST_REPO }}
            TEST_BRANCH: ${{ secrets.TEST_BRANCH }}
            TEST_ACCESSTOKEN: ${{ secrets.TEST_ACCESSTOKEN }}
          run: |
            npm i
            npm test

        - name: Upload Jest integration test report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: Jest-integration-test-report
            path: /home/runner/work/Lucid-Dynamodb/report/integration-test-report.html


