name: License checker

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  module-dependencies-license-checker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Get all dependent module licenses
          run: |
            sudo npm install -g license-checker
            cd ${{ github.workspace }}
            ls
            license-checker --start ./ --summary
            license-checker --csv --out ./module-dependencies-license-report.csv

        - name: Upload module-dependencies license report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: module-dependencies-license-report
            path: ${{ github.workspace }}/module-dependencies-license-report.csv






            