name: markdown-autodocs

on:
  workflow_run:
    workflows:
      - integration-tests
    types:
      - completed

jobs:        
  autoupdate-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - uses: ./ # Uses an action in the root directory
