name: publish-to-npm

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
      
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v1.4.4
          with:
            node-version: '16.2.0'
            registry-url: 'https://registry.npmjs.org'
            scope: '@dineshsonachalam'
        
        - name: Configure Git
          run: |
            git config user.name dineshsonachalam
            git config user.email dineshsonachalam@gmail.com
        
        - name: Bump a package version
          run: |
            npm version patch  
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        
        # Reference: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        - name: Commit files
          run: |
            ls
            date > generated.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated"
            git push
