name: publish-to-npm

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
      
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v1.4.4
          with:
            node-version: '16.2.0'
            registry-url: 'https://registry.npmjs.org'
            scope: '@dineshsonachalam'
        
        - name: Configure Git
          run: |
            git config user.name dineshsonachalam
            git config user.email dineshsonachalam@gmail.com
        
        - name: Bump a package version
          run: |
            cat package.json | grep -i "version"
            npm version patch  
            cat package.json | grep -i "version"
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Apply automatic changes
            branch: ${{ github.head_ref }}

