name: publish-to-npm

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:        
  integration-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Get release version
          run: |
            echo "release_version: "
            echo ${{ github.event.release.tag_name }}

        - name: Install dependencies
          run: npm i
        
        - name: Start integration test
          env: 
            TEST_REPO: ${{ secrets.TEST_REPO }}
            TEST_BRANCH: ${{ secrets.TEST_BRANCH }}
            TEST_ACCESSTOKEN: ${{ secrets.TEST_ACCESSTOKEN }}
          run: npm test

        - name: Upload Jest integration test report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: Jest-integration-test-report
            path: ${{ github.workspace }}/jest_html_reporters.html

  module-dependencies-license-checker:
      needs: integration-tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo npm install -g license-checker
            npm i

        - name: Get all dependent module licenses
          run: |
            license-checker --summary
            license-checker --csv --out ./module-dependencies-license-report.csv

        - name: Upload module-dependencies license report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: module-dependencies-license-report
            path: ${{ github.workspace }}/module-dependencies-license-report.csv

  scan-for-vulnerabilities:
      needs: module-dependencies-license-checker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: |
            npm i
            sudo npm install -g npm-audit-html
        
        - name: Scan for vulnerabilities and report them in a html file
          run: npm audit --json | npm-audit-html --output vulnerabilities-audit-report.html

        - name: Upload vulnerabilities report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: vulnerabilities-audit-report
            path: ${{ github.workspace }}/vulnerabilities-audit-report.html

  size-of-dependencies-stats:
      needs: scan-for-vulnerabilities
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: |
            sudo npm install -g cost-of-modules
            npm i

        - name: Get size of dependencies
          run: cost-of-modules | tee size-of-dependencies.log

        - name: Upload size of dependencies stats to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: size-of-dependencies
            path: ${{ github.workspace }}/size-of-dependencies.log
  
  deploy:
      needs: size-of-dependencies-stats
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Bump a package version
          run: npm --no-git-tag-version version patch
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Bump package version
            branch: ${{ github.head_ref }}
            file_pattern: package.json

        - uses: JS-DevTools/npm-publish@v1
          with:
            token:  ${{ secrets.NPM_ACCESS_TOKEN }}