name: publish-to-npm

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v1.4.4
          with:
            node-version: '16.2.0'
            registry-url: 'https://registry.npmjs.org'
            scope: '@dineshsonachalam'
        
        - name: Configure Git
          run: |
            git config user.email "dineshsonachalam@gmail.com"
            git config user.name "Dinesh Sonachalam"
        
        - name: Bump a package version
          run: |
            npm version patch  
          env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

        - name: Commit files
          run: |
            git commit -m "Add changes" package.json readme.md
        
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}