name: security-audit

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  scan-for-vulnerabilities:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Scan for vulnerabilities and report them in a html file
          run: |
            sudo npm install -g npm-audit-html
            npm i
            npm audit --json | npm-audit-html --output vulnerabilities-audit-report.html

        - name: Upload vulnerabilities report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: vulnerabilities-audit-report
            path: ${{ github.workspace }}/vulnerabilities-audit-report.html






            